---
name: "Apply Terraform"
description: "Apply Terraform for hub-spoke connector"

inputs:
  bucket_name:
    description: "Name of the S3 bucket"
    required: true
  tfvar_file_path:
    description: "Path to the tfvar file"
    required: true
  directory:
    description: "Directory to run Terraform"
    required: true
  component:
    description: "Component name"
    required: true
  master_s3_directory:
    description: "Name of the master s3 directory"
    required: true
  github_pat:
    description: "GitHub PAT for SCM Provider"
    required: true

runs:
  using: "composite"
  steps:
    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.bucket_name }}" \
          -backend-config="key=${{ inputs.master_s3_directory }}/${{ inputs.component }}/terraform.tfstate"

    - name: Terraform Apply
      shell: bash
      working-directory: ${{ inputs.directory }}
      env:
        TF_VAR_github_pat: ${{ inputs.github_pat }}
      run: terraform apply --auto-approve -var-file="${{ inputs.tfvar_file_path }}"
