apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: orbit-folder-dev-main
  namespace: ${argocd_namespace}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          # 1. Target dev clusters
          - clusters:
              selector:
                matchLabels:
                  environment: dev
          # 2. Discover repos with topic and env/dev folder
          - scmProvider:
              github:
                organization: ${github_org}
                tokenRef:
                  secretName: github-token
                  key: token
              filters:
                - repositoryMatch: ".*"
                  pathsExist: [helm/envs/dev/values.yaml]
                  labelMatch: ${github_app_topic}
              cloneProtocol: https
  template:
    metadata:
      name: "{{.repository}}-main-dev"
      labels:
        env: dev
        type: main
      annotations:
        # Enable ArgoCD Image Updater
        argocd-image-updater.argoproj.io/image-list: app=~
        argocd-image-updater.argoproj.io/app.update-strategy: latest
        argocd-image-updater.argoproj.io/app.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/app.helm.image-tag: 'k8s-service.containerImage.tag'
    spec:
      project: default
      source:
        repoURL: "{{.url}}"
        targetRevision: "main"
        path: "helm"
        helm:
          valueFiles:
            - values.yaml
            - envs/dev/values.yaml
      destination:
        server: "{{.server}}"
        namespace: "{{.repository}}-main-dev"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            istio-injection: enabled
            allow-hub-ecr-pull: "true"
