apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: orbit-folder-dev-main
  namespace: ${argocd_namespace}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          # 1. Target dev clusters
          - clusters:
              selector:
                matchLabels:
                  environment: dev
          # 2. Discover repos with topic and env/dev folder
          - scmProvider:
              github:
                organization: ${github_org}
                tokenRef:
                  secretName: github-token
                  key: token
              filters:
                - repositoryMatch: ".*"
                  pathsExist: [env/dev/values.yaml]
                  labelMatch: ${github_app_topic}
  template:
    metadata:
      name: "{{.repository}}-main-dev"
      labels:
        orbit/env: dev
        orbit/type: main
    spec:
      project: default
      source:
        repoURL: "{{.url}}"
        targetRevision: "main"
        path: "."
        helm:
          valueFiles:
            - values.yaml
            - env/dev/values.yaml
      destination:
        server: "{{.server}}"
        namespace: "{{.repository}}-main-dev"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            istio-injection: enabled
