apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: orbit-folder-promoter
  namespace: ${argocd_namespace}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          # 1. Discover Repos
          - scmProvider:
              github:
                organization: ${github_org}
                tokenRef:
                  secretName: github-token
                  key: token
              filters:
                - repositoryMatch: ".*"
                  labelMatch: ${github_app_topic}
          # 2. List Environments (QA, Prod)
          - list:
              elements:
                - env: qa
                - env: prod
  template:
    metadata:
      name: "{{.repository}}-main-{{.env}}"
      labels:
        orbit/env: "{{.env}}"
        orbit/type: stable
    spec:
      project: default
      source:
        repoURL: "{{.url}}"
        targetRevision: "main"
        path: "."
        helm:
          valueFiles:
            - values.yaml
            - env/{{.env}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.repository}}-main-{{.env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
